export const SEARCHING_MOVIE_REQUEST = "SEARCHING_MOVIE_REQUEST";
export const SEARCHING_MOVIE_SUCCESS = "SEARCHING_MOVIE_SUCCESS";
export const SEARCHING_MOVIE_FAILED = "SEARCHING_MOVIE_FAILED";

export const DETAIL_MOVIE_REQUEST = "DETAIL_MOVIE_REQUEST";
export const DETAIL_MOVIE_SUCCESS = "DETAIL_MOVIE_SUCCESS";
export const DETAIL_MOVIE_FAILED = "DETAIL_MOVIE_FAILED";